/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ScheduleRouteImport } from './routes/schedule'
import { Route as ReviewRouteImport } from './routes/review'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ChoresRouteImport } from './routes/chores'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChildrenIndexRouteImport } from './routes/children/index'
import { Route as KidAccessCodeRouteImport } from './routes/kid/$accessCode'
import { Route as ChildrenChildIdRouteImport } from './routes/children/$childId'

const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ScheduleRoute = ScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewRoute = ReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ChoresRoute = ChoresRouteImport.update({
  id: '/chores',
  path: '/chores',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChildrenIndexRoute = ChildrenIndexRouteImport.update({
  id: '/children/',
  path: '/children/',
  getParentRoute: () => rootRouteImport,
} as any)
const KidAccessCodeRoute = KidAccessCodeRouteImport.update({
  id: '/kid/$accessCode',
  path: '/kid/$accessCode',
  getParentRoute: () => rootRouteImport,
} as any)
const ChildrenChildIdRoute = ChildrenChildIdRouteImport.update({
  id: '/children/$childId',
  path: '/children/$childId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chores': typeof ChoresRoute
  '/login': typeof LoginRoute
  '/review': typeof ReviewRoute
  '/schedule': typeof ScheduleRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/children/$childId': typeof ChildrenChildIdRoute
  '/kid/$accessCode': typeof KidAccessCodeRoute
  '/children/': typeof ChildrenIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chores': typeof ChoresRoute
  '/login': typeof LoginRoute
  '/review': typeof ReviewRoute
  '/schedule': typeof ScheduleRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/children/$childId': typeof ChildrenChildIdRoute
  '/kid/$accessCode': typeof KidAccessCodeRoute
  '/children': typeof ChildrenIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chores': typeof ChoresRoute
  '/login': typeof LoginRoute
  '/review': typeof ReviewRoute
  '/schedule': typeof ScheduleRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/children/$childId': typeof ChildrenChildIdRoute
  '/kid/$accessCode': typeof KidAccessCodeRoute
  '/children/': typeof ChildrenIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chores'
    | '/login'
    | '/review'
    | '/schedule'
    | '/settings'
    | '/setup'
    | '/children/$childId'
    | '/kid/$accessCode'
    | '/children/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chores'
    | '/login'
    | '/review'
    | '/schedule'
    | '/settings'
    | '/setup'
    | '/children/$childId'
    | '/kid/$accessCode'
    | '/children'
  id:
    | '__root__'
    | '/'
    | '/chores'
    | '/login'
    | '/review'
    | '/schedule'
    | '/settings'
    | '/setup'
    | '/children/$childId'
    | '/kid/$accessCode'
    | '/children/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChoresRoute: typeof ChoresRoute
  LoginRoute: typeof LoginRoute
  ReviewRoute: typeof ReviewRoute
  ScheduleRoute: typeof ScheduleRoute
  SettingsRoute: typeof SettingsRoute
  SetupRoute: typeof SetupRoute
  ChildrenChildIdRoute: typeof ChildrenChildIdRoute
  KidAccessCodeRoute: typeof KidAccessCodeRoute
  ChildrenIndexRoute: typeof ChildrenIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedule': {
      id: '/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof ScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review': {
      id: '/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof ReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chores': {
      id: '/chores'
      path: '/chores'
      fullPath: '/chores'
      preLoaderRoute: typeof ChoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/children/': {
      id: '/children/'
      path: '/children'
      fullPath: '/children/'
      preLoaderRoute: typeof ChildrenIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kid/$accessCode': {
      id: '/kid/$accessCode'
      path: '/kid/$accessCode'
      fullPath: '/kid/$accessCode'
      preLoaderRoute: typeof KidAccessCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/children/$childId': {
      id: '/children/$childId'
      path: '/children/$childId'
      fullPath: '/children/$childId'
      preLoaderRoute: typeof ChildrenChildIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChoresRoute: ChoresRoute,
  LoginRoute: LoginRoute,
  ReviewRoute: ReviewRoute,
  ScheduleRoute: ScheduleRoute,
  SettingsRoute: SettingsRoute,
  SetupRoute: SetupRoute,
  ChildrenChildIdRoute: ChildrenChildIdRoute,
  KidAccessCodeRoute: KidAccessCodeRoute,
  ChildrenIndexRoute: ChildrenIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
